name:                tasty-megaparsec
version:             0.0.1.0
github:              "keszocze/tasty-megaparsec"
license:             BSD3
author:              "Oliver Keszöcze <info@oliver.keszoecze.de>"
maintainer:          "Oliver Keszöcze <info@oliver.keszoecze.de>"
copyright:           "2023 Oliver Keszöcze"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis: Utility functions for testing Megaparsec parsers with Tasty 
category: Testing, Parsing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/keszocze/tasty-megaparsec#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 9.4.1 && < 9.5
- parser-combinators >= 1.3.0 && < 1.4
- tasty >= 1.4.3 && < 1.5
- tasty-hunit>= 0.12.3 && < 0.13
- tasty-expected-failure >= 0.10.0 && < 0.11

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  tasty-megaparsec-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tasty-megaparsec
