name: Haskell CI (nightly)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Stackage ${{ matrix.resolver }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        resolver: [nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: stack
        uses: freckle/stack-action@v4
        with:
          pedantic: false
          stack-arguments: --resolver ${{ matrix.resolver }} --test --haddock
