name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:

  build:
    if: false
    name: Stackage ${{ matrix.resolver }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        resolver: [lts-21.6, lts-20.26, lts-20.24, lts-19.33, lts-18.28]
        include:
          - resolver: lts-21.6
            haddock: --haddock
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - id: stack
        uses: freckle/stack-action@v4
        with:
          pedantic: false
          stack-arguments: --resolver ${{ matrix.resolver }} ${{ matrix.haddock }}
          cache-prefix: ${{ matrix.resolver }}/
