name: Haskell CI (nightly)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    name: Stackage nightly on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: stack
        uses: freckle/stack-action@v4
        with:
          pedantic: false
          stack-arguments: --resolver nightly --haddock
          cache-prefix: nightly/
